//
// Autogenerated by Thrift Compiler (0.8.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;
var ttypes = module.exports = {};
ttypes.TimeLineType = {
'Inbox' : 1,
'Outbox' : 2,
'ReadNotice' : 3,
'UnReadNotice' : 4
};
ttypes.MsgType = {
'Comment' : 10,
'Post' : 11
};
ttypes.RelationType = {
'Followers' : 21,
'Following' : 22
};
ttypes.GradeCategory = {
'Grade7' : 31,
'Grade8' : 32,
'Grade9' : 33
};
ttypes.AttachType = {
'Normal' : 0,
'Photo' : 1,
'Video' : 2,
'Music' : 3,
'SinaPhoto' : 4
};
var Attach = module.exports.Attach = function(args) {
  this.attachtext = null;
  this.type = null;
  this.attachname = null;
  if (args) {
    if (args.attachtext !== undefined) {
      this.attachtext = args.attachtext;
    }
    if (args.type !== undefined) {
      this.type = args.type;
    }
    if (args.attachname !== undefined) {
      this.attachname = args.attachname;
    }
  }
};
Attach.prototype = {};
Attach.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.attachtext = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.type = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.attachname = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Attach.prototype.write = function(output) {
  output.writeStructBegin('Attach');
  if (this.attachtext) {
    output.writeFieldBegin('attachtext', Thrift.Type.STRING, 1);
    output.writeString(this.attachtext);
    output.writeFieldEnd();
  }
  if (this.type) {
    output.writeFieldBegin('type', Thrift.Type.I32, 2);
    output.writeI32(this.type);
    output.writeFieldEnd();
  }
  if (this.attachname) {
    output.writeFieldBegin('attachname', Thrift.Type.STRING, 3);
    output.writeString(this.attachname);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Msg = module.exports.Msg = function(args) {
  this.mid = null;
  this.msgtext = null;
  this.uid = null;
  this.pushlishTime = null;
  this.type = null;
  this.category = null;
  this.ip = null;
  this.device = null;
  this.attachments = null;
  this.msgdesc = null;
  this.tags = null;
  if (args) {
    if (args.mid !== undefined) {
      this.mid = args.mid;
    }
    if (args.msgtext !== undefined) {
      this.msgtext = args.msgtext;
    }
    if (args.uid !== undefined) {
      this.uid = args.uid;
    }
    if (args.pushlishTime !== undefined) {
      this.pushlishTime = args.pushlishTime;
    }
    if (args.type !== undefined) {
      this.type = args.type;
    }
    if (args.category !== undefined) {
      this.category = args.category;
    }
    if (args.ip !== undefined) {
      this.ip = args.ip;
    }
    if (args.device !== undefined) {
      this.device = args.device;
    }
    if (args.attachments !== undefined) {
      this.attachments = args.attachments;
    }
    if (args.msgdesc !== undefined) {
      this.msgdesc = args.msgdesc;
    }
    if (args.tags !== undefined) {
      this.tags = args.tags;
    }
  }
};
Msg.prototype = {};
Msg.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.mid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.msgtext = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.uid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.pushlishTime = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.I32) {
        this.type = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.I32) {
        this.category = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.STRING) {
        this.ip = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 9:
      if (ftype == Thrift.Type.STRING) {
        this.device = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.attachments = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.Attach();
          elem6.read(input);
          this.attachments.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 11:
      if (ftype == Thrift.Type.STRING) {
        this.msgdesc = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 12:
      if (ftype == Thrift.Type.LIST) {
        var _size7 = 0;
        var _rtmp311;
        this.tags = [];
        var _etype10 = 0;
        _rtmp311 = input.readListBegin();
        _etype10 = _rtmp311.etype;
        _size7 = _rtmp311.size;
        for (var _i12 = 0; _i12 < _size7; ++_i12)
        {
          var elem13 = null;
          elem13 = input.readString();
          this.tags.push(elem13);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Msg.prototype.write = function(output) {
  output.writeStructBegin('Msg');
  if (this.mid) {
    output.writeFieldBegin('mid', Thrift.Type.STRING, 1);
    output.writeString(this.mid);
    output.writeFieldEnd();
  }
  if (this.msgtext) {
    output.writeFieldBegin('msgtext', Thrift.Type.STRING, 2);
    output.writeString(this.msgtext);
    output.writeFieldEnd();
  }
  if (this.uid) {
    output.writeFieldBegin('uid', Thrift.Type.STRING, 3);
    output.writeString(this.uid);
    output.writeFieldEnd();
  }
  if (this.pushlishTime) {
    output.writeFieldBegin('pushlishTime', Thrift.Type.STRING, 5);
    output.writeString(this.pushlishTime);
    output.writeFieldEnd();
  }
  if (this.type) {
    output.writeFieldBegin('type', Thrift.Type.I32, 6);
    output.writeI32(this.type);
    output.writeFieldEnd();
  }
  if (this.category) {
    output.writeFieldBegin('category', Thrift.Type.I32, 7);
    output.writeI32(this.category);
    output.writeFieldEnd();
  }
  if (this.ip) {
    output.writeFieldBegin('ip', Thrift.Type.STRING, 8);
    output.writeString(this.ip);
    output.writeFieldEnd();
  }
  if (this.device) {
    output.writeFieldBegin('device', Thrift.Type.STRING, 9);
    output.writeString(this.device);
    output.writeFieldEnd();
  }
  if (this.attachments) {
    output.writeFieldBegin('attachments', Thrift.Type.LIST, 10);
    output.writeListBegin(Thrift.Type.STRUCT, this.attachments.length);
    for (var iter14 in this.attachments)
    {
      if (this.attachments.hasOwnProperty(iter14))
      {
        iter14 = this.attachments[iter14];
        iter14.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.msgdesc) {
    output.writeFieldBegin('msgdesc', Thrift.Type.STRING, 11);
    output.writeString(this.msgdesc);
    output.writeFieldEnd();
  }
  if (this.tags) {
    output.writeFieldBegin('tags', Thrift.Type.LIST, 12);
    output.writeListBegin(Thrift.Type.STRING, this.tags.length);
    for (var iter15 in this.tags)
    {
      if (this.tags.hasOwnProperty(iter15))
      {
        iter15 = this.tags[iter15];
        output.writeString(iter15);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TimeLine = module.exports.TimeLine = function(args) {
  this.uid = null;
  this.group = null;
  this.mids = null;
  if (args) {
    if (args.uid !== undefined) {
      this.uid = args.uid;
    }
    if (args.group !== undefined) {
      this.group = args.group;
    }
    if (args.mids !== undefined) {
      this.mids = args.mids;
    }
  }
};
TimeLine.prototype = {};
TimeLine.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.uid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.group = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.LIST) {
        var _size16 = 0;
        var _rtmp320;
        this.mids = [];
        var _etype19 = 0;
        _rtmp320 = input.readListBegin();
        _etype19 = _rtmp320.etype;
        _size16 = _rtmp320.size;
        for (var _i21 = 0; _i21 < _size16; ++_i21)
        {
          var elem22 = null;
          elem22 = input.readString();
          this.mids.push(elem22);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TimeLine.prototype.write = function(output) {
  output.writeStructBegin('TimeLine');
  if (this.uid) {
    output.writeFieldBegin('uid', Thrift.Type.STRING, 1);
    output.writeString(this.uid);
    output.writeFieldEnd();
  }
  if (this.group) {
    output.writeFieldBegin('group', Thrift.Type.I32, 2);
    output.writeI32(this.group);
    output.writeFieldEnd();
  }
  if (this.mids) {
    output.writeFieldBegin('mids', Thrift.Type.LIST, 3);
    output.writeListBegin(Thrift.Type.STRING, this.mids.length);
    for (var iter23 in this.mids)
    {
      if (this.mids.hasOwnProperty(iter23))
      {
        iter23 = this.mids[iter23];
        output.writeString(iter23);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

