/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.iko.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MsgType implements org.apache.thrift.TEnum {
  Repost(4),
  Comment(5),
  Post(7);

  private final int value;

  private MsgType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MsgType findByValue(int value) { 
    switch (value) {
      case 4:
        return Repost;
      case 5:
        return Comment;
      case 7:
        return Post;
      default:
        return null;
    }
  }
}
