/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.iko.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TimeLineType implements org.apache.thrift.TEnum {
  Inbox(1),
  Outbox(2),
  At(3),
  Repost(4),
  Comment(5),
  Favorite(6);

  private final int value;

  private TimeLineType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TimeLineType findByValue(int value) { 
    switch (value) {
      case 1:
        return Inbox;
      case 2:
        return Outbox;
      case 3:
        return At;
      case 4:
        return Repost;
      case 5:
        return Comment;
      case 6:
        return Favorite;
      default:
        return null;
    }
  }
}
